theme = "angels-ladder"
baseurl = "http://4679.space/"
languageCode = "en-US"
title = "4679's Blog"
disqusShortname = "4679"

[permalinks]
post = "/:slug/"

[Params]
subtitle = "Nothing Here"
about = "/page/about"
links = "/page/friends"
twitter = "https://twitter.com/4679kun"
weibo = "http://weibo.com/u/1963942417"
github = "https://github.com/4679"
profile = "https://dn-4679kun.qbox.me/head.jpg?imageView2/2/format/webp"
copyright = "Written by 4679kun"
showsRSS = "true"
